### ISSUE TITLE
Remove deprecated SPDX identifiers

### ISSUE THREAD

**Issue by MunsterPlop** [condy0919/spdx.el#10]
Maybe it would be good to eventually remove the deprecated identifiers mentioned at the end of the https://spdx.org/licenses/ page (e.g: GPL-3.0).
I'd rather ask about it first since some projects probably still use those deprecated ids.

**Comment by condy0919** [comment]
Currently the spdx identifier list is fetched from the spdx github repo, and it updates daily. You can take a look at the github ci config.

**Comment by MunsterPlop** [comment]
I had a look and I think what might be a good solution is to have an option `spdx-ignore-deprecated`  when set to `t` would take into account the json key `isDeprecatedLicenseId` and ignore entries where the value is `true` filtering the list in spdx-* functions.

**Comment by lassik** [comment]
Currently we have `spdx-data-license-identifiers`. Could move the deprecated ones into a separate list `spdx-data-deprecated-license-identifiers`. I can make make the PR to do that.

**Comment by lassik** [comment]
Implemented in PR #11

**Comment by condy0919** [comment]
A new user option added. `spdx-ignore-deprecated`

**Comment by MunsterPlop** [comment]
Awesome, thank you for your work!
