### ISSUE TITLE
SPDX-FileCopyrightText file tag

### ISSUE THREAD

**Issue by nbarrientos** [condy0919/spdx.el#14]
Hi,

Is there any reason behind `spdx-copyryight-format` prefixing the copyright holder with `Copyright ` instead of using the `SPDX-FileCopyrightText` file tag?

https://spdx.github.io/spdx-spec/v2.3/file-tags/
https://spdx.github.io/spdx-spec/v2.3/file-information/#8.8

Something like:

```diff
@@ -215,7 +215,7 @@ defun spdx-get-existing-copyright
 
 (defun spdx-copyright-format ()
   "Prompt for SPDX Copyright line, with a guess for the default line."
-  (let ((prefix "Copyright "))
+  (let ((prefix "SPDX-FileCopyrightText: "))
     (concat prefix
             (read-from-minibuffer
              prefix

```

Thanks in advance.

**Comment by nbarrientos** [comment]
Putting the prefix behind a `defcustom` would do the job, too :)

**Comment by condy0919** [comment]
Thanks for pointing it out. I never know that before.

**Comment by condy0919** [comment]
Implemented in https://github.com/condy0919/spdx.el/commit/bd68c0bb6958b647f955600c490d395179713cb3

**Comment by lassik** [comment]
`spdx-copyright-name` - a better name would be `spdx-copyright-prefix`?

**Comment by condy0919** [comment]
> `spdx-copyright-name` - a better name would be `spdx-copyright-prefix`?

Applied.
