### ISSUE TITLE
spdx-insert-spdx-copyright doesn't work

### ISSUE THREAD

**Issue by tagoh** [condy0919/spdx.el#16]
I use spdx.el with project 0.9.8 (builtin) from elpa.  When I call spdx-insert-spdx-copyright, the exception happens like:
```
Debugger entered--Lisp error: (wrong-type-argument stringp (Git "~/.emacs.d/"))
  spdx--guess-project-name()
  spdx-get-default-copyright-holder()
  spdx-make-default-copyright()
  spdx-copyright-format()
  tempo-insert((spdx-copyright-format) nil)
  #f(compiled-function (elt) #<bytecode -0x7e58d072a36e2af>)((spdx-copyright-format))
  tempo-insert-template(tempo-template-spdx-copyright nil)
  tempo-template-spdx-copyright()
  spdx-insert-spdx-copyright()
  funcall-interactively(spdx-insert-spdx-copyright)
  command-execute(spdx-insert-spdx-copyright record)
  execute-extended-command(nil "spdx-insert-spdx-copyright" nil)
  funcall-interactively(execute-extended-command nil "spdx-insert-spdx-copyright" nil)
  command-execute(execute-extended-command)
```

What am I missing?

**Comment by tagoh** [comment]
Correctly speaking, this happens only for files **under a directory managed by Git** regardless of the state that they are actually managed by Git or not.

**Comment by lassik** [comment]
I found the bug. In `spdx--guess-project-name` the expression `(funcall (symbol-function 'project-current))` returns a list like `(vc Git "~/path/to/project/root/")`. The code expects a list like `(one-symbol "~/path/to/project/root/")`.
