### ISSUE TITLE
Wrong type argument error in empty LICENSE file

### ISSUE THREAD

**Issue by galeo** [condy0919/spdx.el#4]
Thanks for this convenient package. When try to call `spdx-insert-spdx` in an empty `LICENSE` file, it would lead to `wrong-type-argument` error. Here is the backtrace log:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("[ \11]*\\'" nil)
  comment-add(nil)
  spdx-comment-start()
  eval((spdx-comment-start))
  tempo-insert((spdx-comment-start) nil)
  #f(compiled-function (elt) #<bytecode 0x1ffe90c31235>)((spdx-comment-start))
  mapc(#f(compiled-function (elt) #<bytecode 0x1ffe90c31235>) ((spdx-comment-start) (spdx-license-format) (spdx-comment-end) > n>))
  tempo-insert-template(tempo-template-spdx nil)
  tempo-template-spdx()
  spdx-insert-spdx()
  funcall-interactively(spdx-insert-spdx)
  call-interactively(spdx-insert-spdx record nil)
  command-execute(spdx-insert-spdx record)
  ...
```

**Comment by condy0919** [comment]
An empty LICENSE file has not comment syntax, so it's expected. It's mainly used in those modes derived from `prog-mode`

**Comment by galeo** [comment]
Should this error be handled? Or prompt that it is unavailable in current mode?

**Comment by condy0919** [comment]
Yes, thanks for advice.

It should be fixed in 20e48f3b439ff2bfd24b6f68bcb8bf802b1f40e3

**Comment by galeo** [comment]
Thanks.

**Comment by mattiasb** [comment]
I stumbled over this as well, found this issue, upgraded and now I get an actionable explanation. That's great!

However, if I call `comment-or-uncomment-region` I get an option to set the comment syntax.

Maybe a call to `(comment-normalize-vars)` instead of the `(spdx--ensure-comment-syntax-defined)` defun would be eveen better? :)

**Comment by condy0919** [comment]
Good tips
