### ISSUE TITLE
Insert only SPDX id at point

### ISSUE THREAD

**Issue by MunsterPlop** [condy0919/spdx.el#9]
I often need to just insert the SPDX id string, no comment/template.
I know you can kinda use ivy/selectrum/etc actions to do that but spdx-insert-spdx always inserts `;;` by default which I have to delete everytime.
Of course you can also just copy paste from the minibuffer but it would be more convenient to have, for example a `spdx-insert-spdx-only` function or something like that to just insert the spdx id at the current point.

**Comment by condy0919** [comment]
Check it :-)

**Comment by MunsterPlop** [comment]
Thank you for taking the time !
I just checked, and I wasn't very clear so it's my bad, but I meant only the ID without `SPDX-License-Identifier: ` in front.
Apologies for the inconvenience...

**Comment by condy0919** [comment]
`spdx-insert-spdx-identifier-only` added. I'm curious about your use case why the `SPDX-License-Identifier: ` prefix is unnecessary?

**Comment by MunsterPlop** [comment]
I'm regularly contributing to https://github.com/lukesampson/scoop various buckets (like [extras](https://github.com/lukesampson/scoop-extras), etc...) and I have to put the SPDX id in a json field everytime I create a new package manifest, so being able to add it from a list without having to remember the precise id OTOMH is pretty useful.

**Comment by condy0919** [comment]
thanks for explanation

**Comment by MunsterPlop** [comment]
Thank you very much for your work! It's perfect.
